# 代理模式: 'static' 静态代理（Proxy.txt），'dynamic' 动态代理（NSTProxy）（推荐）
proxy_mode: dynamic
# 动态代理通道ID（仅proxy_mode为dynamic时需要）
nstproxy_channel: ''
# 动态代理密码（仅proxy_mode为dynamic时需要）
nstproxy_password: ''
# 每个账号执行多少次脚本
script_run_count: 5
# 运行模式（1=安全模式，2=极速模式）
run_mode: 1 
